# Generated by Django 4.2.1 on 2023-05-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributorsourcemodel",
            name="product_currency_selector",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
