# Generated by Django 4.2.1 on 2023-05-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_distributorsourcemodel_product_currency_selector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distributorsourcemodel",
            name="product_currency_selector",
        ),
        migrations.AddField(
            model_name="distributorsourcemodel",
            name="currency",
            field=models.CharField(default="EUR", max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="distributorsourcemodel",
            name="including_vat",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="distributorsourcemodel",
            name="product_name_selector",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="distributorsourcemodel",
            name="product_picture_url_selector",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="distributorsourcemodel",
            name="product_price_selector",
            field=models.CharField(max_length=1024),
        ),
    ]
