# Generated by Django 4.2.1 on 2023-05-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "search",
            "0003_remove_distributorsourcemodel_product_currency_selector_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="distributorsourcemodel",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
